;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-paren
	c-electric-slash
	evil-append
	evil-backward-char
	evil-backward-word-begin
	evil-change
	evil-delete
	evil-delete-char
	evil-exit-visual-state
	evil-find-char
	evil-force-normal-state
	evil-forward-char
	evil-forward-word-begin
	evil-goto-first-line
	evil-insert
	evil-multiedit--change
	evil-next-line
	evil-normal-state
	evil-open-below
	evil-paste-after
	evil-previous-line
	evil-replace
	org-ctrl-c-ctrl-c
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	evil-downcase
	evil-multiedit-abort
	evil-visual-char
	iedit-switch-to-mc-mode
	switch-to-buffer
	))
